name: 'Terraform apply'
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        options:
          - dev
          - live
        default: 'dev'
permissions:
  id-token: write
  contents: write
jobs:
  plan:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Provision runner
        uses: nationalarchives/org-actions-provision-runner@5657f48ecd0fd31bfe857919149f1fdc690d53ed # v1.0.1
        with:
          wiz-sensor-token: ${{ secrets.WIZ_SENSOR_TOKEN }}
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Configure AWS credentials for Lambda
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_NUMBER }}:role/DiagramTerraformRole
          aws-region: eu-west-2
          role-session-name: TerraformRole
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
      - name: Terraform Plan
        id: plan
        run: |
          terraform init 
          terraform workspace select ${{ github.event.inputs.environment }}
          terraform plan
  apply:
    runs-on: ubuntu-latest
    needs:
      - plan
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Provision runner
        uses: nationalarchives/org-actions-provision-runner@5657f48ecd0fd31bfe857919149f1fdc690d53ed # v1.0.1
        with:
          wiz-sensor-token: ${{ secrets.WIZ_SENSOR_TOKEN }}
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          repository: nationalarchives/DiAGRAM-terraform
      - name: Configure AWS credentials for Lambda
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_NUMBER }}:role/DiagramTerraformRole
          aws-region: eu-west-2
          role-session-name: TerraformRole
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
      - name: Run apply
        run: |
          terraform init
          terraform workspace select ${{ github.event.inputs.environment }}
          terraform apply --auto-approve
      - id: next-tag
        run: echo next-version=$(curl -s $GITHUB_API_URL/repos/nationalarchives/DiAGRAM-terraform/tags | jq -r '.[0].name' | awk -F. -v OFS=. '{ $3++; print }') >> "$GITHUB_OUTPUT"
      - run: |
          git tag ${{ steps.next-tag.outputs.next-version }}
          git push origin ${{ steps.next-tag.outputs.next-version }}
          git branch -f release-${{ github.event.inputs.environment }} HEAD
          git push -f origin release-${{ github.event.inputs.environment }}
      - run: pip install boto3
      - name: Send failure message
        if: failure()
        run: python .github/scripts/send_message.py
        env:
          MESSAGE: ":warning: DiAGRAM-terraform deploy failed for ${{ github.event.inputs.environment }}"
      - name: Send success message
        run: python .github/scripts/send_message.py
        env:
          MESSAGE: ":white_check_mark: DiAGRAM-terraform deploy successful for ${{ github.event.inputs.environment }}"
