name: 'Terraform apply'
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment'
        required: true
        options:
          - dev
          - prod
        default: 'dev'
permissions:
  id-token: write
  contents: write
jobs:
  apply:
    uses: nationalarchives/dr2-github-actions/.github/workflows/terraform_apply.yml@main
    with:
      repo-name: dr2-terraform-environments
      environment: ${{ github.event.inputs.environment }}
      project: diagram
    secrets:
      WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
      ACCOUNT_NUMBER: ${{ secrets.ACCOUNT_NUMBER }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      TERRAFORM_ROLE: ${{ secrets.TERRAFORM_ROLE }}

