name: 'Terraform check'
on:
  push:
permissions:
  id-token: write
  contents: write
jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Configure AWS credentials for Lambda
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          role-to-assume: ${{ secrets.DEV_TERRAFORM_ROLE }}
          aws-region: eu-west-2
          role-session-name: TerraformRole
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: 1.11.3
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check --recursive
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Select dev workspace
        run: terraform workspace select dev
      - name: Terraform Validate
        id: validate
        run: terraform validate
